### ISSUE TITLE
Використання Браунського корпусу української мови як джерела для Mozilla Common Voice

### ISSUE THREAD

**Issue by strixaluco** [brown-uk/corpus#2]
Дуже дякую вам за роботу над Браунським корпусом української мови.

Вам напевно відомо про проект Mozilla Common Voice ¹ ², що покликаний зробити технології розпізнавання голосу доступними для всіх. Станом на сьогодні готовність української мови у проекті досягла 50% і хоча мені не відомі фактичні деталі справи, можна припустити, що може мати місце певна нестача текстового матеріалу для начитування. Хай там що, спала мені думка використати ваш Браунський корпус української мови у якості текстового джерела для Common Voice, але виникло питання законності.

БрУК розповсюджується за ліцензією Creative Commons BY-NC-SA ³, проте деякі джерела використаних текстів розповсюджують свої твори за несумісними з Creative Commons ліцензіями. Наприклад, Газета.ua ⁴, Крим.Реалії ⁵ або The Insider ⁶. Я навів абсолютно випадковий перелік джерел, просто перевірив ті, що спали на очі.

Ви домовлялись з джерелами про особливі умови використання текстів чи я невірно розумію що саме зі складу БрУКу ліцензується за Creative Commons BY-NC-SA? Буду дуже вдячним якщо ви зможете прояснити ці питання і розвіяти мої сумніви :)

Сподіваюсь ми зможемо скористатись вашим чудовим проектом для розбудови іншого чудового проекту.

¹ https://voice.mozilla.org/uk
² https://voice-sprint.mozilla.community/
³ https://github.com/brown-uk/corpus
⁴ https://gazeta.ua/ (внизу сторінки)
⁵ https://ua.krymr.com/p/4554.html
⁶ http://www.theinsider.ua/reprinting-rules/

**Comment by dchaplinsky** [comment]
Добрий день.
Чи вам потрібні саме проанотовані тексти для вашої роботи?

Якщо просто тексти українською, то думаю, що ми зможемо знайти вам безліч текстів з ліцензією, що вам підійде.

**Comment by strixaluco** [comment]
Проанотованість не є необхідною умовою. Підійдуть будь які тексти, що написані сучасною українською мовою і є суспільним надбанням.
Згідно з рекомендаціями ¹ проекту, найкращими джерелами є подкасти, стенограми, кіносценарії та будь-що, що може містити повсякденну розмовну лексику.

¹ https://voice-sprint.mozilla.community/contributing/

**Comment by dchaplinsky** [comment]
В мене є велика колекція текстів, назбирана у рамках проекту UberCorpus:
http://lang.org.ua/en/corpora/#anchor4

Там різні джерела, можете взяти їх та натренувати на пробу, якщо якість буде достатня, то я зможу поговорити з правовласниками та спитати на дозвіл. Ну й там вікіпедія є, в неї проблем з ліцензією нема взагалі.

Тексти викладені з перемішаними реченнями, але якщо потрібні оригінальні або якісь відокремлені джерела – дайте знати.

Якщо шукати конкретно стенограми, то я можу спитати в знайомого з ВР, скоріш за все, можна взяти усі їх стенограми (сама рада + комітети) доволі легко.
Ще є варіант знайти субтитри українською для фільмів, їх має бути багато.

**Comment by strixaluco** [comment]
Дуже дякую.
Трохи відхилились від початкової теми, може перейдемо у якийсь профільний форум? Наприклад, https://r2u.org.ua/forum/?

**Comment by dchaplinsky** [comment]
Можна там, можна тут, можна в пошті, мені особливої різниці нема

24 черв. 2018 р. о 15:17 strixaluco <notifications@github.com> пише:

**Comment by dchaplinsky** [comment]
http://data.rada.gov.ua/open/data/stenogram
До речі.

**Comment by strixaluco** [comment]
Перепрошую за затримку, трохи пізніше напишу.

**Comment by vstarko** [comment]
Дякую, це цікаво на майбутнє.

    On Monday, June 25, 2018, 11:47:42 AM GMT+3, Dmitry Chaplinsky <notifications@github.com> wrote:  
 
 
http://data.rada.gov.ua/open/data/stenogram
До речі.

**Comment by tarasinf** [comment]
@strixaluco Як у вас справи з Мозілою, чи підійшли стенограми з ВР?

**Comment by strixaluco** [comment]
@tarasinf Зовсім забув про це. Дякую за нагадування, можливо знайду можливість зайнятись цим незабаром.

**Comment by tarasinf** [comment]
@strixaluco пишіть, як будуть новини. Якщо можу чимось допомогти - буду радий!

**Comment by strixaluco** [comment]
@tarasinf Дякую. На жаль, поки не можемо завантажувати тексти, бо інструмент збору речень ще доробляється, але дуже скоро планують запустити його бету: https://discourse.mozilla.org/t/we-want-your-feedback-improving-the-sentence-collection/30358/45

**Comment by velmyshanovnyi** [comment]
полагодили інструмент завантаження текстів!!!
пробував вантажити,
по 10к ВАЛІДНИХ рядків за один раз "скормлюється" (за 30...60хв)

https://common-voice.github.io/sentence-collector/#/

поточний статус:
Українська
302.266 total sentences.
10.000 unreviewed sentences.
7.746 validated sentences.

продовжую там у вільний час валідацію речень, для начитки.

хто це читатиме, стукніть мені в телеграм, є декілька ідей ))
https://t.me/velmyshanovnyi

**Comment by egorsmkv** [comment]
На всякий випадок, для історії більше, напишу, що розпізнаванням української вже давно займаємося і результати можна знайти тут: https://github.com/egorsmkv/speech-recognition-uk
